---
# Update Time: 2024-04-27 10:00
version: "3.4"

x-defines:
  service-common: &service-common-ref
    networks: [network_cluster]
    restart: on-failure
  env-common: &env-common-ref
    NO_PROXY: ${NO_PROXY:-localhost,127.0.0.1,::1}
    TZ: ${TZ:-Asia/Shanghai}    
  env-proxy: &env-proxy-ref
    HTTP_PROXY: ${OPENCLASH_HTTP_PROXY}
    HTTPS_PROXY: ${OPENCLASH_HTTP_PROXY}
    http_proxy: ${OPENCLASH_HTTP_PROXY}
    https_proxy: ${OPENCLASH_HTTP_PROXY}
  deploy-common: &deploy-common-ref
    mode: replicated
    replicas: 1
    restart_policy:
      condition: on-failure
      delay: 5s      
  placement-default: &placement-default-ref
    placement:
      constraints:
        - node.labels.type == vm
        - node.labels.ai == true
  driver-common: &driver-common-ref
    type: nfs
    o: addr=${NFS_SERVER},rw,nfsvers=4

services:
  # ------------------------------------------------------------
  # Xiaoai GPT
  # ------------------------------------------------------------
  xiaogpt1:
    <<: *service-common-ref
    # image-ref: yihong0618/xiaogpt:v2.84
    image: registry.${DOMAIN_SWARM}:${EXTERNAL_PORT}/yihong0618/xiaogpt:v2.84
    command: --config=/config/config.json
    environment:
      <<: [*env-common-ref, *env-proxy-ref]
      PROXY: ${OPENCLASH_HTTP_PROXY}
    volumes:
      - nfs_xiaogpt_config1:/config
      - nfs_xiaogpt_src:/app/xiaogpt
    logging:
      driver: fluentd
      options:
        tag: docker.ai.xiaogpt1
        fluentd-async-connect: "true"
    deploy:
      labels:
        - homepage.group=AI & Automation
        - homepage.name=XiaoGPT #1
        - homepage.icon=https://www.${DOMAIN_NAS}:${EXTERNAL_PORT}/images/services/xiaogpt.png
        - homepage.description=XiaoGPT on Bed Room
        - homepage.ping=xiaogpt1
        - homepage.weight=20
      <<: [*deploy-common-ref, *placement-default-ref]
  xiaogpt2:
    <<: *service-common-ref
    # image-ref: yihong0618/xiaogpt:v2.84
    image: registry.${DOMAIN_SWARM}:${EXTERNAL_PORT}/yihong0618/xiaogpt:v2.84
    command: --config=/config/config.json
    environment:
      <<: [*env-common-ref, *env-proxy-ref]
      PROXY: ${OPENCLASH_HTTP_PROXY}
    volumes:
      - nfs_xiaogpt_config2:/config
      - nfs_xiaogpt_src:/app/xiaogpt
    logging:
      driver: fluentd
      options:
        tag: docker.ai.xiaogpt2
        fluentd-async-connect: "true"
    deploy:
      labels:
        - homepage.group=AI & Automation
        - homepage.name=XiaoGPT #2
        - homepage.icon=https://www.${DOMAIN_NAS}:${EXTERNAL_PORT}/images/services/xiaogpt.png
        - homepage.description=XiaoGPT on Living Room
        - homepage.ping=xiaogpt2
        - homepage.weight=21
      <<: [*deploy-common-ref, *placement-default-ref]
  xiaogpt3:
    <<: *service-common-ref
    # image-ref: yihong0618/xiaogpt:v2.84
    image: registry.${DOMAIN_SWARM}:${EXTERNAL_PORT}/yihong0618/xiaogpt:v2.84
    command: --config=/config/config.json
    environment:
      <<: [*env-common-ref, *env-proxy-ref]
      PROXY: ${OPENCLASH_HTTP_PROXY}
    volumes:
      - nfs_xiaogpt_config3:/config
      - nfs_xiaogpt_src:/app/xiaogpt
    logging:
      driver: fluentd
      options:
        tag: docker.ai.xiaogpt3
        fluentd-async-connect: "true"
    deploy:
      labels:
        - homepage.group=AI & Automation
        - homepage.name=XiaoGPT #3
        - homepage.icon=https://www.${DOMAIN_NAS}:${EXTERNAL_PORT}/images/services/xiaogpt.png
        - homepage.description=XiaoGPT on Children Room
        - homepage.ping=xiaogpt3
        - homepage.weight=22
      <<: [*deploy-common-ref, *placement-default-ref]

  # ------------------------------------------------------------
  # FastGPT
  # ------------------------------------------------------------
  fastgpt:
    <<: *service-common-ref
    # image-ref: ghcr.io/labring/fastgpt:latest
    image: registry.${DOMAIN_SWARM}:${EXTERNAL_PORT}/labring/fastgpt:latest
    environment:
      <<: [*env-common-ref, *env-proxy-ref]
      DEFAULT_ROOT_PSW: ${FASTGPT_DEFAULT_ROOT_PSW}
      OPENAI_BASE_URL: ${FASTGPT_OPENAI_BASE_URL}
      CHAT_API_KEY: ${FASTGPT_CHAT_API_KEY}
      DB_MAX_LINK: ${FASTGPT_DB_MAX_LINK}
      TOKEN_KEY: ${FASTGPT_TOKEN_KEY}
      ROOT_KEY: ${FASTGPT_ROOT_KEY}
      FILE_TOKEN_KEY: ${FASTGPT_FILE_TOKEN_KEY}
      MONGODB_URI: ${FASTGPT_MONGODB_URI}
      PG_URL: ${FASTGPT_PG_URL}
      AXIOS_PROXY_HOST: ${FASTGPT_AXIOS_PROXY_HOST}
      AXIOS_PROXY_PORT: ${FASTGPT_AXIOS_PROXY_PORT}
    # volumes:
    #   - nfs_fastgpt_config:/app/data
    logging:
      driver: fluentd
      options:
        tag: docker.ai.fastgpt
        fluentd-async-connect: "true"
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.fastgpt.rule=Host(`fastgpt.${DOMAIN_SWARM}`,`fastgpt.${DOMAIN_EMERGENCY}`)
        - traefik.http.routers.fastgpt.entrypoints=websecure
        - traefik.http.routers.fastgpt.service=fastgpt
        - traefik.http.routers.fastgpt.middlewares=auth,cors-headers@file,normal-chain@file
        - traefik.http.services.fastgpt.loadbalancer.server.port=3000
        - homepage.group=AI & Automation
        - homepage.name=FastGPT
        - homepage.icon=https://www.${DOMAIN_NAS}:${EXTERNAL_PORT}/images/services/fastgpt.png
        - homepage.href=https://fastgpt.${DOMAIN_SWARM}:${EXTERNAL_PORT}/
        - homepage.description=基于LLM大模型的AI知识库问答平台
        - homepage.siteMonitor=http://fastgpt:3000
        - homepage.weight=1
      <<: [*deploy-common-ref, *placement-default-ref]

  # ------------------------------------------------------------
  # One API
  # ------------------------------------------------------------
  oneapi:
    <<: *service-common-ref
    # image-ref: justsong/one-api:v0.6.7-alpha.4
    image: registry.${DOMAIN_SWARM}:${EXTERNAL_PORT}/justsong/one-api:v0.6.7-alpha.4
    command: --log-dir /app/logs
    environment:
      <<: [*env-common-ref, *env-proxy-ref]
      # SQL_DSN: ${ONEAPI_SQL_DSN}  # 修改此行，或注释掉以使用 SQLite 作为数据库
      REDIS_CONN_STRING: ${ONEAPI_REDIS_CONN_STRING}
      SYNC_FREQUENCY: 60
      SESSION_SECRET: ${ONEAPI_SESSION_SECRET}
    volumes:
      - nfs_oneapi_data:/data
      - nfs_oneapi_log:/app/logs
    logging:
      driver: fluentd
      options:
        tag: docker.ai.oneapi
        fluentd-async-connect: "true"
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.oneapi.rule=Host(`oneapi.${DOMAIN_SWARM}`,`oneapi.${DOMAIN_EMERGENCY}`)
        - traefik.http.routers.oneapi.entrypoints=websecure
        - traefik.http.routers.oneapi.service=oneapi
        - traefik.http.routers.oneapi.middlewares=auth,cors-headers@file,normal-chain@file
        - traefik.http.services.oneapi.loadbalancer.server.port=3000
        - homepage.group=AI & Automation
        - homepage.name=OneAPI
        - homepage.icon=https://www.${DOMAIN_NAS}:${EXTERNAL_PORT}/images/services/oneapi.png
        - homepage.href=https://oneapi.${DOMAIN_SWARM}:${EXTERNAL_PORT}/
        - homepage.description=OpenAI接口管理&分发系统
        - homepage.siteMonitor=http://oneapi:3000
        - homepage.weight=2
      <<: [*deploy-common-ref, *placement-default-ref]

  # ------------------------------------------------------------
  # GPT Academic
  # ------------------------------------------------------------
  gptacademic:
    <<: *service-common-ref
    # image-ref: ghcr.io/binary-husky/gpt_academic_nolocal:master
    image: registry.${DOMAIN_SWARM}:${EXTERNAL_PORT}/binary-husky/gpt_academic_nolocal:master
    command: >
      bash -c "python3 -u main.py"
    environment:
      <<: [*env-common-ref, *env-proxy-ref]
      API_KEY: ${GPTACADEMIC_API_KEY}
      API_URL_REDIRECT: ${GPTACADEMIC_API_URL_REDIRECT}
      USE_PROXY: ${GPTACADEMIC_USE_PROXY}
      # proxies: { "http": "socks5h://localhost:10880", "https": "socks5h://localhost:10880", }
      LLM_MODEL: ${GPTACADEMIC_LLM_MODEL}
      AVAIL_LLM_MODELS: $GPTACADEMIC_AVAIL_LLM_MODELS}
      WEB_PORT: ${GPTACADEMIC_WEB_PORT}
      ADD_WAIFU: ${GPTACADEMIC_ADD_WAIFU}
      THEME: ${GPTACADEMIC_THEME}
      DEFAULT_WORKER_NUM: ${GPTACADEMIC_DEFAULT_WORKER_NUM}
      AUTHENTICATION: ${GPTACADEMIC_AUTHENTICATION}
    logging:
      driver: fluentd
      options:
        tag: docker.ai.gptacademic
        fluentd-async-connect: "true"
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.gptacademic.rule=Host(`gptacademic.${DOMAIN_SWARM}`,`gptacademic.${DOMAIN_EMERGENCY}`)
        - traefik.http.routers.gptacademic.entrypoints=websecure
        - traefik.http.routers.gptacademic.service=gptacademic
        - traefik.http.routers.gptacademic.middlewares=auth,cors-headers@file,normal-chain@file
        - traefik.http.services.gptacademic.loadbalancer.server.port=${GPTACADEMIC_WEB_PORT}
        - homepage.group=AI & Automation
        - homepage.name=GPT Academic
        - homepage.icon=https://www.${DOMAIN_NAS}:${EXTERNAL_PORT}/images/services/academic.png
        - homepage.href=https://gptacademic.${DOMAIN_SWARM}:${EXTERNAL_PORT}/
        - homepage.description=GPT 学术优化
        - homepage.siteMonitor=http://gptacademic:${GPTACADEMIC_WEB_PORT}
        - homepage.weight=3
      <<: [*deploy-common-ref, *placement-default-ref]

  # ------------------------------------------------------------
  # Ollama WebUI
  # ------------------------------------------------------------
  ollama-webui:
    <<: *service-common-ref
    # image-ref: ghcr.io/open-webui/open-webui:main
    image: registry.${DOMAIN_SWARM}:${EXTERNAL_PORT}/open-webui/open-webui:main
    environment:
      <<: [*env-common-ref, *env-proxy-ref]
      OLLAMA_API_BASE_URL: ${OLLAMAWEBUI_OLLAMA_API_BASE_URL}
      COMFYUI_BASE_URL: ${OLLAMAWEBUI_COMFYUI_BASE_URL}
      WEBUI_SECRET_KEY: ${OLLAMAWEBUI_WEBUI_SECRET_KEY}
      HF_ENDPOINT: ${OLLAMAWEBUI_HF_ENDPOINT}
      ENABLE_IMAGE_GENERATION: "true"
    volumes:
      - nfs_ollama-webui_data:/app/backend/data
    logging:
      driver: fluentd
      options:
        tag: docker.ai.ollama
        fluentd-async-connect: "true"
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.ollama.rule=Host(`ollama.${DOMAIN_SWARM}`,`ollama.${DOMAIN_EMERGENCY}`)
        - traefik.http.routers.ollama.entrypoints=websecure
        - traefik.http.routers.ollama.service=ollama
        - traefik.http.routers.ollama.middlewares=auth,cors-headers@file,normal-chain@file
        - traefik.http.services.ollama.loadbalancer.server.port=8080
        - homepage.group=AI & Automation
        - homepage.name=Ollama WebUI
        - homepage.icon=ollama.png
        - homepage.href=https://ollama.${DOMAIN_SWARM}:${EXTERNAL_PORT}/
        - homepage.description=Ollama WebUI
        - homepage.siteMonitor=http://ollama:${GPTACADEMIC_WEB_PORT}
        - homepage.weight=4
      <<: [*deploy-common-ref, *placement-default-ref]

networks:
  network_cluster:
    external: true

volumes:
  # NFS
  nfs_xiaogpt_src:
    driver: local
    driver_opts:
      <<: *driver-common-ref
      device: :${NFS_DEVICE}/ai/xiaogpt/src/xiaogpt
  nfs_xiaogpt_config1:
    driver: local
    driver_opts:
      <<: *driver-common-ref
      device: :${NFS_DEVICE}/ai/xiaogpt/config1
  nfs_xiaogpt_config2:
    driver: local
    driver_opts:
      <<: *driver-common-ref
      device: :${NFS_DEVICE}/ai/xiaogpt/config2
  nfs_xiaogpt_config3:
    driver: local
    driver_opts:
      <<: *driver-common-ref
      device: :${NFS_DEVICE}/ai/xiaogpt/config3
  nfs_fastgpt_config:
    driver: local
    driver_opts:
      <<: *driver-common-ref
      device: :${NFS_DEVICE}/ai/fastgpt/data
  nfs_oneapi_data:
    driver: local
    driver_opts:
      <<: *driver-common-ref
      device: :${NFS_DEVICE}/ai/oneapi/data
  nfs_oneapi_log:
    driver: local
    driver_opts:
      <<: *driver-common-ref
      device: :${NFS_DEVICE}/ai/oneapi/log
  nfs_ollama-webui_data:
    driver: local
    driver_opts:
      <<: *driver-common-ref
      device: :${NFS_DEVICE}/ai/ollama-webui/data
...